title = "LuaEnum"

gitSourceBranch = "main"

[docusaurus]
organizationName = "Shae A"
projectName = "LuaEnum"
url = "https://corecii.github.io"
baseUrl = "/lua-enum-simple/"
tagline = "A simple Enum type"